### ISSUE TITLE
Bug: Doesn't Launch

### ISSUE THREAD

**Issue by AlphaLeoli** [mega12345mega/NBT-Editor#123]
```java 
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod nbteditor
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:529)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
    at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
    at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:527)
    ... 3 more
```
Minecraft: 1.21.1
Mod: 2.0.2.999

my gf crashed like this too but this fixes itself randomly

**Comment by mega12345mega** [comment]
Are you using a custom client or something? The error itself is bizarre, but on top of that the fact that it fixes itself randomly is even more bizarre
Also make sure that you're using the `.jar` from the `Artifacts.zip/libs/` folder, not `Artifacts.zip/devlibs/`

**Comment by AlphaLeoli** [comment]
Yes I am using that jar
And I was using Boze but again it fixes itself randomly. On top of that, my gf gets this error though she doesn't use boze just fabric

**Comment by mega12345mega** [comment]
Looking at the code, this seems basically impossible, unless this is a 1.21.1 thing (highly unlikely) - since I haven't started 1.21.1 support yet, I'm not even setup to look at 1.21.1's code yet
Can you either upload the `.jar` file you're using or check the `.accesswidener` file? To check the file, rename the `.jar` to `.zip`, then open the file `nbteditor.accesswidener` with Notepad - post if it says `accessWidener v1 intermediary` or `accessWidener v1 named` at the top of the file.
Presumably you're 100% sure that "fixing itself randomly" isn't actually just you downloaded the next dev build and happened to grab the correct `.jar` that time?

**Comment by AlphaLeoli** [comment]
well i am on 1.21.1
and no, i haven't changed jars at all I've only downloaded the next build once
also it says `accessWidener	v1	intermediary`

**Comment by mega12345mega** [comment]
What is your fabric loader version?
Can you send the jar file in `.minecraft\libraries\net\fabricmc\fabric-loader\<the fabric loader version you're using>`, so I can see exactly what the code being executed looks like? Thanks

I just did a bunch of unrelated testing in several Minecraft versions (including 1.21.1), and I never saw this issue :/

**Comment by AlphaLeoli** [comment]
doesn't happen anymore
