### ISSUE TITLE
The game crashed whilst ticking screen

### ISSUE THREAD

**Issue by cheslin23t** [mega12345mega/NBT-Editor#37]
Here's my crash file, it says it's from this mod, so I'm making an issue here.
(and yes I have an intel i3)
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-02-20 06:31:53
Description: Ticking screen

java.lang.ClassCastException: class com.luneruniverse.minecraft.mod.nbteditor.screens.CreativeTab$CreativeTabGroup cannot be cast to class net.minecraft.class_4185 (com.luneruniverse.minecraft.mod.nbteditor.screens.CreativeTab$CreativeTabGroup and net.minecraft.class_4185 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a396c1e)
	at net.minecraft.class_419.handler$zza000$init(class_419.java:553)
	at net.minecraft.class_419.method_25426(class_419.java:30)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_635.method_10839(class_635.java:143)
	at net.minecraft.class_2535.method_10768(class_2535.java:423)
	at net.minecraft.class_412.method_25393(class_412.java:116)
	at net.minecraft.class_310.method_1572(class_310.java:1855)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_310.method_1574(class_310.java:1855)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_419.handler$zza000$init(class_419.java:553)
	at net.minecraft.class_419.method_25426(class_419.java:30)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_635.method_10839(class_635.java:143)
	at net.minecraft.class_2535.method_10768(class_2535.java:423)
	at net.minecraft.class_412.method_25393(class_412.java:116)
	at net.minecraft.class_310.method_1572(class_310.java:1855)
	at net.minecraft.class_437.method_25412(class_437.java:492)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_412
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_310.method_1574(class_310.java:1855)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/redstone-tweaks-2-2-1.zip, file/clean-redstone-v2-5-0.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3162378080 bytes (3015 MiB) / 3825205248 bytes (3648 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21796.74
	Virtual memory used (MB): 19902.32
	Swap memory total (MB): 9745.20
	Swap memory used (MB): 1768.18
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=45 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		authme: Auth Me 5.0.0
			cloth-config: Cloth Config v9 9.0.94
				cloth-basic-math: cloth-basic-math 0.6.1
		autoclicker-fabric: Auto Clicker 1.19.3-1.5.0-build.20
		carpet: Carpet Mod 1.4.91
		fabric-api: Fabric API 0.70.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.1+f1e4495b85
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.10+99f9db8085
			fabric-command-api-v1: Fabric Command API (v1) 1.2.20+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.16+99f9db8085
			fabric-commands-v0: Fabric Commands (v0) 0.2.37+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.45+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.2+33a4e2d785
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.38+f1e4495b85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.40+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.6+99f9db8085
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.9+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.29+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.27+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.15+99f9db8085
			fabric-networking-v0: Fabric Networking (v0) 0.3.32+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.1+f1e4495b85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.2+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.1+afca2f3e85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.24+99f9db8085
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.1+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.11+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.13+f1e4495b85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.2.0+1d37d50285
		fabricloader: Fabric Loader 0.14.12
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.13.1
		litematica_printer: Litematica Printer ${version}
		malilib: MaLiLib 0.14.0
		minecraft: Minecraft 1.19.3
		nbteditor: NBT Editor 1.10.0
		xaerominimap: Xaero's Minimap 23.1.0
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.9664, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/redstone-tweaks-2-2-1.zip (incompatible), file/clean-redstone-v2-5-0.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

**Comment by mega12345mega** [comment]
This appears to be the same as Issue #34, only the conflict is with a different mod. Just like Vivecraft, it appears one of the mods you have loaded is expecting the first element on the main menu screen to be button, which is not the case when NBT Editor is loaded. (Refer to the other issue for more information.) I'll make sure to have this fixed in the next update!

In the meantime, you could do a binary search on your mod list, to find which mod (or mods?) is causing the conflict. If that mod isn't particularly important, than you could remove it for now. Additionally, I would recommend submitting an issue on that mod's GitHub, since any mod that modifies the main menu with non-button elements could have issues (here's Vivecraft's [fix](https://github.com/ferriarnus/VivecraftMod/commit/640429e411b659e6208c1d17c501cf31810ba044)). Thanks!

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which fixes this!
