### ISSUE TITLE
Commands not working + Translation update

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#73]
**Translation update**
https://github.com/Xantrisse/NBT-Editor-Mod-Polish-translation

**Commands not working**
Error:
[13:39:05] [Server thread/INFO]: Gracz Xantrisse dołączył do gry
[13:39:06] [Render thread/INFO]: Started 1 worker threads
[13:39:06] [Render thread/WARN]: Ambiguity between arguments [cfind, --keep-searching] and [cfind, filter] with inputs: [--keep-searching]
[13:39:06] [Render thread/WARN]: Ambiguity between arguments [cfind, -k] and [cfind, filter] with inputs: [-k]
[13:39:06] [Render thread/WARN]: Ambiguity between arguments [cusagetree, --all] and [cusagetree, command] with inputs: [--all]
[13:39:06] [Render thread/WARN]: Ambiguity between arguments [cusagetree, -a] and [cusagetree, command] with inputs: [-a]
[13:39:07] [Render thread/ERROR]: Error executing task on Client
java.lang.RuntimeException: Error getting method
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Reflection.getMethod(Reflection.java:132) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Reflection.lambda$getOptionalMethod$2(Reflection.java:136) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Reflection$1.get(Reflection.java:149) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.commands.ClientCommandManager.lambda$createDispatcher$3(ClientCommandManager.java:128) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Version$VersionSwitch.get(Version.java:54) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.commands.ClientCommandManager.createDispatcher(ClientCommandManager.java:134) ~[nbteditor-1.12.2.jar:?]
	at net.minecraft.class_634.handler$cdc002$nbteditor$onGameJoin(class_634.java:6912) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:440) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.15.3-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.class_8673.method_29091()
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Reflection$MethodInvoker.<init>(Reflection.java:86) ~[nbteditor-1.12.2.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.multiversion.Reflection.getMethod(Reflection.java:130) ~[nbteditor-1.12.2.jar:?]
	... 20 more
[13:39:08] [Render thread/INFO]: Loaded 56 advancements
[13:39:11] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2036ms or 40 ticks behind
[13:39:47] [Server thread/INFO]: Saving and pausing game...

The list of modifications is in the image:
![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/bd0999e0-2ee9-4e83-80bf-2201f17403ef)

![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/bfff76e0-2618-47d0-90cb-4583196615b5)
![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/2a3d8b59-292f-48fa-af1a-748a3fff2bd8)
![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/cf194661-2cf9-4479-90cc-9ced46367278)

Minecraft 1.20.2
fabric-loader-0.15.3-1.20.2

**Comment by mega12345mega** [comment]
🤦 I forgot to test commands outside of the development environment apparently, since I forgot what I tested and didn't from a month ago
Luckily the keybinds still work, and the alpha version's commands work (I believe)
I'm most likely going to include the fix for this bug in the 1.20.4 support version that I'm currently working on
I may be able to release a dev build that fixes this in a moment (will link here when that happens)

Thanks for the translation update!

**Comment by Xantrisse** [comment]
Thx
![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/8e9b8327-6b34-4cf8-a992-e3ff78b9e5a6)
![image](https://github.com/mega12345mega/NBT-Editor/assets/149414796/cc3e6057-3465-45d6-9f71-70492d282924)

**Comment by mega12345mega** [comment]
Just released v1.12.3, which fixes this and includes the updated language file!
