### ISSUE TITLE
Adding hover-event "show-text" on books crashes the game

### ISSUE THREAD

**Issue by inon-13** [mega12345mega/NBT-Editor#91]
[07:07:25] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NoSuchFieldError: field_46601
	at com.luneruniverse.minecraft.mod.nbteditor.screens.widgets.FormattedTextFieldWidget$InternalTextFieldWidget$EventEditorWidget$HoverAction.toEvent(FormattedTextFieldWidget.java:99) ~[nbteditor-1.13.0.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.widgets.FormattedTextFieldWidget$InternalTextFieldWidget$EventEditorWidget.updateOk(FormattedTextFieldWidget.java:189) ~[nbteditor-1.13.0.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.widgets.FormattedTextFieldWidget$InternalTextFieldWidget$EventEditorWidget.lambda$new$0(FormattedTextFieldWidget.java:142) ~[nbteditor-1.13.0.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.configurable.ConfigValueDropdown.lambda$setValue$1(ConfigValueDropdown.java:119) ~[nbteditor-1.13.0.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.configurable.ConfigValueDropdown.setValue(ConfigValueDropdown.java:119) ~[nbteditor-1.13.0.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.configurable.ConfigValueDropdown.method_25402(ConfigValueDropdown.java:92) ~[nbteditor-1.13.0.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.widgets.TranslatedGroupWidget.method_25402(TranslatedGroupWidget.java:66) ~[nbteditor-1.13.0.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at com.luneruniverse.minecraft.mod.nbteditor.screens.OverlaySupportingScreen.method_25402(OverlaySupportingScreen.java:110) ~[nbteditor-1.13.0.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 16 more

**Comment by sirblazzit** [comment]
This happens to me in the display editor as well.

**Comment by mega12345mega** [comment]
I've now fixed this in v2.0.0!
